[build]
    command = "yarn build"
    publish = "dist"
    functions = "functions"

[dev]
    targetPort = 8080
    port = 8888

[[plugins]]
    package = "./plugins/cache"

# Netlify subdomain
[[redirects]]
    from = "https://rcucnw5pfx25wcc8xp4c28w359bsk74mdgy8u.netlify.app/*"
    to = "https://ege.celikci.me/:splat"
    status = 301
    force = true

[[redirects]]
    from = "https://celikci.me/*"
    to = "https://ege.celikci.me/:splat"
    status = 301
    force = true

[[redirects]]
    from = "https://ege.celikci.me/notes/20251201173255"
    to = "https://ege.celikci.me/notes/20251201143255"
    status = 302
    force = true

# Bots
[[redirects]]
    from = "/wp-login.php"
    to = "https://www.fbi.gov"
    status = 302
    force = true

# Favicon
[[redirects]]
    from = "/assets/images/touch/*"
    to = "/assets/images/favicon/:splat"
    status = 301
    force = true

# 404s
[[redirects]]
    from = "*"
    to = "/404"
    status = 404